sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: jBls1lZJyxSK3ECdCY9Cc/ebYFIA+vk21mCdbdGrANpPEV0DD9Uzf/zQ14K8Ah8Moi6sVjqbGt7A+J9NsM/FiJSHyjibToV9Sx6XLb7Rmn032Plc0QloiafYVqJbC1eoUX657oONyN41NDzZo8iShLta2nfEh0wk4AdWZ7D3CGzzSOyEr6isKYiKdDNqejHEtDRcq+nhHemK3yaCSYUBWEp3rtDWgqMmGiASn10u8cJRKk5ggzkgWbfB2E+X//tfAh9sZ13IBDmFaMTyttqTblmJduFA4Q5bijfM5qfuJS/Rn05IjF3uesNHVAJHdO8krA2+fNel/S9mOKI4H4wAbv+sTvB93w8GSpvNcTtTcoTBEOPoHN0mSX4IJmaIzo5VmCXXfaqJ8gyJPnF9zfL2ghQs+NoKCYHxeIFA4pOZCTy7Gd+cNw88nVv2r3TYTOU9aGqoEPikmtKPlBjF4TQN29nIpjP775fu7cGQB2lmSn0A310OCkrYIyLM7Vww1e2AClyZolKR8/IWDlDNmD8Ay4ByjP6rg0lByJEb209IC8EAIqzImAdKaNGkUfSTSJCG8icH4Ruh+yFAkn7piTxpzuGlboU5LbpndRbaUxgENQKtP3dQKOsTdhtU2c0LHKsb+cJqjqgvxrAygc41UFMroYx71/B4wwSgvgaEcDwAPK0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Shakespeare-s-Sonnets_1041
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy